//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchoolTR14WR
{
  using System;
  using System.Collections.Generic;
  using System.Linq;

  public partial class Client
  {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Client()
    {
      this.ClientService = new HashSet<ClientService>();
      this.Tag = new HashSet<Tag>();
    }

    public int ID { get; set; }
    public string LastName { get; set; }
    public string FirstName { get; set; }
    public string Patronymic { get; set; }
    public string GenderCode { get; set; }
    public string Phone { get; set; }
    public string PhotoPath { get; set; }
    public System.DateTime Birthday { get; set; }
    public string Email { get; set; }
    public System.DateTime RegistrationDate { get; set; }
    //мужское женское
    public string GenderName
    {
      get
      {
        return Gender.Name;
      }
    }
    //регистрация Date
    public string RegistrationDateString
    {
      get
      {
        if (this.RegistrationDate != null)
        {
          return RegistrationDate.ToShortDateString();
        }
        else
          return "";
      }
    }
    //День рождегия
    public string BirthdayString
    {
      get
      {
        if (this.Birthday != null)
        {
          return Birthday.ToShortDateString();
        }
        else
          return "";
      }
    }
    //кол-во посещений
    public int VisitCount
    {
      get
      {
        var datelist = ClientService.Where(x => x.ClientID == this.ID).ToList();
        return datelist.Count;
      }
    }
    //последний заход вход
    public string LastEntry
    {
      get
      {
        var entryList = ClientService
            .Where(x => x.ClientID == this.ID)
            .OrderByDescending(x => x.StartTime)
            .ToList();
        if (entryList.Any())
          return entryList.First().StartTime.ToShortDateString();
        else
          return "нет";
      }
    }


    public virtual Gender Gender { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ClientService> ClientService { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Tag> Tag { get; set; }
  }
}
